config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :products do
    resources :user_carts, only: [:new, :create]
  end
  resources :user_carts, only: [:index, :destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :carts
  has_many :users, through: :user_carts
  belongs_to :user
  has_many_attached :photos
  validates :bike, :localization, :price, :bike_condition, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :products
  has_many :user_carts
  has_many :products, through: :user_carts
end

app/models/user_cart.rb
class UserCart < ApplicationRecord
  STATUS = ['pending', 'approved', 'denied']
  belongs_to :user
  belongs_to :product
  has_many :products
  validates :status, inclusion: { in: STATUS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  #include Pundit

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  #private

#   def skip_pundit?
#     devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
#   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @products_home = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
    @user_cart = UserCart.new
    #authorize @product

  end

  def new
    @product = Product.new
    #authorize @product
  end

  def edit
    #authorize @product
  end

  def create
    @product = Product.new(product_params)
    #authorize @product
    @product.user = current_user
    if @product.save
      redirect_to @product, notice: "Product was sucessfully created."
    else
      render :new
    end
  end

  def update
    #authorize @product
    if @product.update(product_params)
      redirect_to @product, notice: "Product was sucessfully updated."
    else
      render :edit
    end
  end

  def destroy
    #authorize @product
    @product.destroy
    redirect_to products_url, notice: "Product was sucessfully destroyed."
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:bike, :localization, :price, :bike_condition, photos: [])
  end
end

app/controllers/user_carts_controller.rb
class UserCartsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @user_cart = UserCart.new
  end

  def create
    @product = Product.find(params[:product_id])
    @user_cart = UserCart.new(user_cart_params)
    #authorize @user_cart
    @user_cart.product = @product
    @user_cart.user = current_user
    if @user_cart.save
      redirect_to user_carts_path(@user_cart)
    else
      render 'products/show'
    end
  end

  def index
    @products = Product.all
    #@user_carts = policy_scope(UserCart)
    @user_carts = current_user.user_carts

  end

  def destroy
    @user_cart = UserCart.find(params[:id])
    @user_cart.destroy
    redirect_to user_carts_path
  end

  private

  def user_cart_params
    params.require(:user_cart).permit(:product_id, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent a Bike</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.rickysbicycletours.co.uk/wp-content/uploads/2019/04/Rickys-Bicycle-Tours-Edinurgh-Mountain-Adventure-City-Bike-Hire-ADVENTURE-TOURS-SLIDER.jpg);">
  <div class="container">
    <h1>Rent a Bike brings <strong>provide the bike you need</strong>!</h1>
    <p>Enjoy a weekend tour without having to buy a bike.</p>
    <a class="btn btn-primary" href="/products">Rent now</a>
  </div>
</div>

<div class="container mb-5">
<h4>------------------------------------------------- Some bikes you'll find <strong>here.</strong> ------------------------------------------------</h4>
</div>

<div class="container justify-content-center mb-5">
  <div class="cards">
    <div class="card-home" style="background-image: url(https://decathlonpro.vteximg.com.br/arquivos/ids/2601150/--caloi-vulcan-29-preta-m1.jpg?v=637431148584430000)">
     <span class='btn btn-dark' disabled>Caloi</span>
     </div>
     <div class="card-home" style="background-image: url(https://upload4.bikepointsc.com.br/g/g55384_1.jpg)">
     <span class='btn btn-dark' disabled>Cannondale</span>
     </div>
     <div class="card-home">
     <span><%= link_to 'Log in to see more', new_user_session_path, class:"btn btn-info" %> </span>
     </div>

</div>

  </div>
<div class="container mb-5">
<h4>-------------------------------------------------------------------------------------------------------------------------------</h4>
</div>

app/views/products/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-6 mb-5">
<%= simple_form_for(@product) do |f| %>
  <%= f.input :bike, label: "Your bike model" %>
  <%= f.input :localization, label: "The city where your bike is" %>
  <%= f.input :price %>
  <%= f.input :bike_condition, as: :radio_buttons, collection: ['new', 'used', 'under maintence'] %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>
</div>
<hr>

<div class="container mt-4">
  <%= link_to "Back", products_path, class:"btn btn-secondary" %>
</div>
</div>

app/views/products/edit.html.erb
<div class="container mt-4">
  <h1>Edit</h1>
  <%= render "form", task: @product %>
</div>

app/views/products/index.html.erb
<div class="container mt-4">
    <h1>All products</h1>
    <p></p>

    <div class="container mt-5 mb-5">
      <%= link_to "Create", new_product_path, class:"btn btn-primary" %>
      <%= link_to "Back", root_path, class:"btn btn-secondary" %>
    </div>
    <div class="cards">
      <% @products.each do |product| %>
        <div class="card-trip">
        <%= cl_image_tag product.photos.first.key, :crop=>"fill"%>
        <div class="card-trip-infos">
        <div>
        <h2><%= link_to product.bike, product_path(product) %></h2>
        <p><%= product.localization %></p>
        <% if product.available? %>
          <%= link_to 'Available', products_path(product), class:"btn btn-outline-primary" %>
        <% else %>
          <td><button type="button" class="btn btn-outline-dark" disabled>Not Available</button></td>
        <% end %>
        <% if product.user == current_user %>
          <%= link_to "Edit", edit_product_path(product), class:"btn btn-outline-primary" %></td>
          <%= link_to "Delete",
                                    product,
                                    method: :delete,
                                    data: { confirm: "Are you sure?" }, class:"btn btn-outline-primary" %></td>
        <% end %>
        </div>
        <h2 class="card-trip-pricing">$<%= product.price %></h2>
        </div>
        </div>
      <% end %>
    </div>
</div>

app/views/products/new.html.erb
<div class="container mt-4">
  <h1>Publish</h1>
  <%= render "form", task: @product %>
</div>

app/views/products/show.html.erb
<div class="container mt-4 text-center">
  <div class="row">
    <div class="col-sm-12">
      <div class="well">
        <% @product.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill, radius: 60 %>
        <% end %>
      </div>
    </div>
  </div>

    <div class="row mt-4">
      <div class="col-sm-12">
        <div class="panel panel-default text-center">
          <h4><%= @product.bike %></h4>
        </div>
      </div>
    </div>

    <div class="row">
        <div class="col-sm-12 mb-4">
          <div class="well default text-left">
            <h5><%= @product.localization %></h5>
            <h5>Price: $<%= @product.price %></h5>
            <h5>Condition: <%= @product.bike_condition %></h5>
          </div>
        </div>
        <div class="row justify-content-center">


      <div class="col-sm-6">
      <div class="card position-sticky top-0">
          <div class="p-1 bg-light bg-opacity-10">
          <%= simple_form_for [@product, @user_cart] do |f| %>
            <div class="row justify-content-center">
                <div class="col-md-6">
                <%= f.hidden_field :status, value: 'pending' %>

            <br />
            <%= f.submit "Book Now", id: "btn_book", class: "btn btn-primary" %>
        <% end %>

            <hr>
            <div class="d-flex justify-content-between mb-4 small">
              <span>TOTAL</span> <strong class="text-dark">
                    <%= @product.price %>

              </strong>
            </div>
                      </div>
        </div>
      </div>

    </div>
</div>

<div class="container mt-5">
  <%= link_to "Back", products_path, class:"btn btn-secondary" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright <i class="fa-solid fa-copyright"></i> 2022 Rent a Bike Company - Todos os direitos reservados
  </div>
</div> %>


<footer class="text-center text-white" style="background-color: #f1f1f1;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-dark" href="http://localhost:3000">RentaBike.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid" align-items-left>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "Bike" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bikes", products_path, class: "nav-link" %>
          </li>
          <%= link_to user_carts_path do %>
            <li class="nav-item fa-solid fa-cart-shopping w-120 p-3"></li>
          <% end %>
          <li class="nav-item dropdown">
            <%= image_tag "bike.webp", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= link_to "My reservations", "#", class: "dropdown-item" %>
              <%= link_to "Post product", new_product_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/user_carts/index.html.erb
<div class="container">
    <h1 class="h3 mb-5 mt-2">These are the Bikes you will rent</h1>
    <div class="row justify-content-center">


      <div class="col-md-6 ">
      <div class="card position-sticky top-0">
          <div class="p-1 bg-light bg-opacity-10">
          <% current_user.user_carts.each do |cart| %>
          <div class='row'>
          <div class="card-title mb-3 image-container"> <%= cl_image_tag cart.product.photos.first.key, height: 100, width: 125, crop: :fill, radius: 20 %> </div>
            <h6 class="card-title mb-3"><%= cart.product.bike %> - Localization: <%= cart.product.localization %></h6>
            </div>
            <div class="d-flex justify-content-between mb-1 small">
              <span>Subtotal:</span> <span> $<%= cart.product.price %> </span>
              <%= link_to 'X', user_cart_path(cart), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
            </div>
            <% end %>

            <hr>
            <div class="d-flex justify-content-between mb-4 small">
              <span>TOTAL:</span> <strong class="text-dark">
              $<% sum = 0 %>
              <% current_user.user_carts.each do |p| %>
              <% price = p.product.price  %>
              <% sum+=price  %>

              <% end %>
              <%= sum %>
                         </strong>
            </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-5 mb-4">
    <%= link_to "Checkout", products_path, class:"btn btn-primary" %>
    </div>
                      </div>
        </div>
      </div>
    </div>


    <div class="container mt-4 mb-5">
    <%= link_to "Back", products_path, class:"btn btn-secondary" %>
    </div>
  </div>